language: go
sudo: false
matrix:
  include:
  - go: tip
  allow_failures:
  - go: tip
script:
- "./.travis/build-all.sh"
deploy:
  provider: releases
  api_key:
    secure: iKIMgO6tCjAjcZevW1t4NOvGf/vNetjYCEtobiOApEW0vENYr5TWhs8VPKd1isina304YLBMdeCooVaXdOKRZRsX/Cy5H3p565N5iPC06uYWwj3vJXO6Rw7gyOeL6gblI7ozWCWmhIsA4XwnAegEITM5TXBhhEzlOBI7C4G0x+CN4ptMChCkikxD1FMdsHK6zFdk2wo/vsU+WlSrhGtjXyzqS+6kVR4CSTmeHbsf/gOSpDWSkSbSEXEmA/mxkCRlUHylHVStgCLu2ghwEw+1SxFFeedQPOOkqwlTZxn1H7F4M1D6Y+KvQOMaedgiICPE7PyfwDn1h0ko6BIo13nzCm3+50yM7wQb25M522o3Tfx+ciT87NUGEA9tCr/dEcm2KkszDPwM4wUjVlVZfsB3iPgQ+axpS3+TfTIO/abRj5e0GFGwkr+dU1t/XPHJlc7CvbRHPSavbnFUUSR7NoNW5dcZzrxp4TI4y0zZt00BGF/PboRzNO8sJ/6BsPr/uICznb5356BYqDr5aJDiaBXHyvkwMj+mhtD1uODT3DOUWIgJv5Yf5YZeaQJhhdMY8ffMJkdFKhIiEhwjgldr/rUXcL29npVyUwCrIebcFdm1k4v0uH5YhJC8yhfuUxNM15G+hznNW1wQOOMfJ12DPBROecmuyhUfF5v/QQiNk5WtV2A=
  file_glob: true
  file: simple-vpn-*
  skip_cleanup: true
  on:
    tags: true
